#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Devel-StackTrace
Version  : 2.04
Release  : 27
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.04.tar.gz
Summary  : 'An object representing a stack trace'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Devel-StackTrace-license = %{version}-%{release}
Requires: perl-Devel-StackTrace-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
# NAME
Devel::StackTrace - An object representing a stack trace
# VERSION
version 2.04

%package dev
Summary: dev components for the perl-Devel-StackTrace package.
Group: Development
Provides: perl-Devel-StackTrace-devel = %{version}-%{release}
Requires: perl-Devel-StackTrace = %{version}-%{release}

%description dev
dev components for the perl-Devel-StackTrace package.


%package license
Summary: license components for the perl-Devel-StackTrace package.
Group: Default

%description license
license components for the perl-Devel-StackTrace package.


%package perl
Summary: perl components for the perl-Devel-StackTrace package.
Group: Default
Requires: perl-Devel-StackTrace = %{version}-%{release}

%description perl
perl components for the perl-Devel-StackTrace package.


%prep
%setup -q -n Devel-StackTrace-2.04
cd %{_builddir}/Devel-StackTrace-2.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Devel-StackTrace
cp %{_builddir}/Devel-StackTrace-2.04/LICENSE %{buildroot}/usr/share/package-licenses/perl-Devel-StackTrace/05919092457d405d691079df2084f6f3eef31ade
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::StackTrace.3
/usr/share/man/man3/Devel::StackTrace::Frame.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Devel-StackTrace/05919092457d405d691079df2084f6f3eef31ade

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Devel/StackTrace.pm
/usr/lib/perl5/vendor_perl/5.34.0/Devel/StackTrace/Frame.pm
