#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Devel-StackTrace
Version  : 2.05
Release  : 41
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.05.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.05.tar.gz
Summary  : 'An object representing a stack trace'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Devel-StackTrace-license = %{version}-%{release}
Requires: perl-Devel-StackTrace-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# NAME
Devel::StackTrace - An object representing a stack trace
# VERSION
version 2.05

%package dev
Summary: dev components for the perl-Devel-StackTrace package.
Group: Development
Provides: perl-Devel-StackTrace-devel = %{version}-%{release}
Requires: perl-Devel-StackTrace = %{version}-%{release}

%description dev
dev components for the perl-Devel-StackTrace package.


%package license
Summary: license components for the perl-Devel-StackTrace package.
Group: Default

%description license
license components for the perl-Devel-StackTrace package.


%package perl
Summary: perl components for the perl-Devel-StackTrace package.
Group: Default
Requires: perl-Devel-StackTrace = %{version}-%{release}

%description perl
perl components for the perl-Devel-StackTrace package.


%prep
%setup -q -n Devel-StackTrace-2.05
cd %{_builddir}/Devel-StackTrace-2.05
pushd ..
cp -a Devel-StackTrace-2.05 buildavx2
popd
pushd ..
cp -a Devel-StackTrace-2.05 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Devel-StackTrace
cp %{_builddir}/Devel-StackTrace-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Devel-StackTrace/332d116af5f367dbb8afcc56fcf53650d3b76bc8 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::StackTrace.3
/usr/share/man/man3/Devel::StackTrace::Frame.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Devel-StackTrace/332d116af5f367dbb8afcc56fcf53650d3b76bc8

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
